exec(open("imp_statements.py").read())

#m = CNNModel()
m = torch.hub.load('pytorch/vision:v0.6.0', 'resnet18', pretrained=True)
loss = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(m.parameters(), lr=0.01)
# scheduler  = torch.optim.lr_scheduler.StepLR(optimizer, 25, gamma=0.001, last_epoch=-1)
m.conv1 = nn.Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
m.fc = nn.Linear(in_features=512, out_features=18, bias=True)
m.load_state_dict(torch.load('State Dict'))
